//
//  ListProductsModels.swift
//  RetailStore
//
//  Created by Rahul Mane on 21/07/18.
//  Copyright (c) 2018 developer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListProducts{
    
    // MARK: Use cases
    enum Fetch{
        //vc-> inter
        struct Request{}
        
        //inter->pres
        struct Response{
            var products : [String : [Product]]?
            var error : ProductStoreError?
        }
        
        //prse-vc
        struct ProductViewModel{
            struct DisplayedProduct{
                var id: String
                var name: NSAttributedString
                var price: NSAttributedString
                var images: [String]
            }
            var displayedProducts : [String : [DisplayedProduct]]
        }
        
        struct ErrorViewModel{
            var title : String
            var message : String
        }
    }
}
