//
//  ListProductsWorker.swift
//  RetailStore
//
//  Created by Rahul Mane on 21/07/18.
//  Copyright (c) 2018 developer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListProductsWorker{
    private var productStore: ProductStoreProtocol
    
    init(productStore : ProductStoreProtocol) {
        self.productStore = productStore
    }
    
    func fetchAll(completionHandler: @escaping ProductsStoreFetchProductsCompletionHandler){
        //we can do extra business logic here like joining multiple entities.
        productStore.fetch(completionHandler: completionHandler)
    }
}
