//
//  CartWorker.swift
//  RetailStore
//
//  Created by Rahul Mane on 21/07/18.
//  Copyright (c) 2018 developer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CartWorker{
    private var cartStore : CartStoreProtocol
    
    init(cartStore : CartStoreProtocol) {
        self.cartStore = cartStore
    }
    
    //MARK: Work
    func fetchAll(completionHandler : @escaping CartStoreFetchProductsCompletionHandler){
        cartStore.fetchAll(completionHandler: completionHandler)
    }
    
    func removeProduct(productId : String, completionHandler : @escaping CartStoreRemoveProductCompletionHandler){
        cartStore.remove(productId: productId,completionHandler: completionHandler)
    }
}
