//
//  ShowProductRouter.swift
//  RetailStore
//
//  Created by Rahul Mane on 21/07/18.
//  Copyright (c) 2018 developer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowProductRoutingLogic{
}

protocol ShowProductDataPassing{
  var dataStore: ShowProductDataStore? { get }
}

class ShowProductRouter: NSObject, ShowProductRoutingLogic, ShowProductDataPassing{
  weak var viewController: ShowProductViewController?
  var dataStore: ShowProductDataStore?
  
  // MARK: Routing
}
