//
//  ShowProductWorker.swift
//  RetailStore
//
//  Created by Rahul Mane on 21/07/18.
//  Copyright (c) 2018 developer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ShowProductWorker{
    private var cartStore: CartStoreProtocol
    
    init(cartStore : CartStoreProtocol) {
        self.cartStore = cartStore
    }
    
    //MARK : Work
    func addToCart(product : Product,completionHandler : @escaping CartStoreAddProductCompletionHandler){
        cartStore.fetch(productId: product.id) { (result) in
            switch(result){
            case .success(var dbproduct):
                dbproduct.count = dbproduct.count + 1
                self.cartStore.update(product: dbproduct, completionHandler: completionHandler)
            case .failure(_) :
                self.cartStore.add(product: product, completionHandler: completionHandler)
            }
        }
    }
}
