//
//  ShowProductModels.swift
//  RetailStore
//
//  Created by Rahul Mane on 21/07/18.
//  Copyright (c) 2018 developer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowProduct{
    enum ShowProductUsedBy{
        case productList
        case cart
    }
    
    enum Fetch{
        struct Request{}
        
        struct Response{
            var product : Product?
            var usedBy : ShowProductUsedBy = .productList
        }
        
        struct DisplayedProductViewModel{
            enum ProductTableRows {
                case icon(String)
                case name(NSAttributedString)
                case price(NSAttributedString)
                case addToCart
            }
            var id: String
            var tableRepresentation : [ProductTableRows]
        }
        
        struct ErrorViewModel{
            var title : String
            var message : String
        }
    }
    
    enum AddToCart{
        struct Request{}
        
        struct Response{
            var product : Product?
            var error : CartStoreError?
        }
        
        struct DisplayedProductViewModel{
            var title : String
            var message : String
        }
        
        struct ErrorViewModel{
            var title : String
            var message : String
        }
    }
}
